project_id = "fhmyhvrejofybzdgzxdc"

[functions.fetch-wallet-balances]
verify_jwt = true

[functions.fetch-token-prices]
verify_jwt = false

[functions.fetch-yield-opportunities]
verify_jwt = false

[functions.ai-defi-assistant]
verify_jwt = false

[functions.wormhole-portfolio-fetcher]
verify_jwt = false

[functions.fetch-defi-yields]
verify_jwt = false

[functions.wormhole-execute-swap]
verify_jwt = false

[functions.wormhole-execute-yield]
verify_jwt = false

[functions.wormhole-execute-bridge]
verify_jwt = false
